{
  "openapi": "3.0.0",
  "info": {
    "title": "COVID Modeling",
    "description": "The COVID Modeling UI was developed to help policy makers explore hypothetical intervention strategies to reduce the impact of COVID-19. It provides a common interface and language to run simulations against multiple models at the same time. This API is intended to facilitate automation, e.g. running weekly simulations with the same parameters, and integration with other tools.",
    "version": "0.0.6",
    "license": {"name": "MIT License", "url": "https://mit-license.org/"}
  },
  "servers": [{"url": "/api"}],
  "security": [{"token": [], "session": []}],
  "tags": [
    {
      "name": "simulations",
      "description": "Running simulations and retrieving results"
    },
    {"name": "users", "description": "User management and authentication"}
  ],
  "paths": {
    "/simulations": {
      "get": {
        "description": "Retrieves list of simulations",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "array",
                  "items": {"$ref": "#/components/schemas/SimulationSummary"}
                }
              }
            }
          }
        },
        "operationId": "getSimulations",
        "tags": ["simulations"]
      },
      "post": {
        "description": "Schedule new simulation",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {"$ref": "#/components/schemas/NewModelRunConfig"},
                  {"$ref": "#/components/schemas/NewSimulationConfig"}
                ]
              },
              "examples": {
                "custom": {
                  "summary": "Run simulation for a single model using a custom format",
                  "value": {
                    "model_slug": "sir-ode-python",
                    "config": {
                      "p": [0.5, 0.25],
                      "u0": [0.99, 0.01, 0],
                      "tspan": [0, 10000]
                    }
                  }
                },
                "common": {
                  "summary": "Run simulation for a single model using the common format with complete control over parameters",
                  "value": {
                    "model_slug": "mrc-ide-covid-sim",
                    "config": {
                      "region": "US",
                      "subregion": "US-AK",
                      "parameters": {
                        "calibrationDate": "2020-03-06",
                        "calibrationCaseCount": 0,
                        "calibrationDeathCount": 0,
                        "r0": null,
                        "interventionPeriods": [
                          {
                            "startDate": "2020-03-06",
                            "socialDistancing": "aggressive",
                            "schoolClosure": "aggressive",
                            "caseIsolation": "aggressive",
                            "voluntaryHomeQuarantine": "aggressive",
                            "reductionPopulationContact": 0
                          }
                        ]
                      }
                    }
                  }
                },
                "simplified": {
                  "summary": "Run simulation for multiple models using the simplified format used by the UI",
                  "value": {
                    "regionID": "US",
                    "subregionID": "US-AK",
                    "label": "Simulation",
                    "customCalibrationDate": "2020-03-06",
                    "interventionPeriods": [
                      {
                        "startDate": "2020-03-06",
                        "socialDistancing": "aggressive",
                        "schoolClosure": "aggressive",
                        "caseIsolation": "aggressive",
                        "voluntaryHomeQuarantine": "aggressive",
                        "reductionPopulationContact": 0
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "required": ["id"],
                  "properties": {"id": {"type": "integer"}}
                }
              }
            }
          },
          "422": {
            "description": "Invalid configuration",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "required": ["error"],
                  "properties": {"error": {"type": "string"}}
                }
              }
            }
          }
        },
        "operationId": "postSimulations",
        "tags": ["simulations"]
      }
    },
    "/user/token": {
      "post": {
        "description": "Generates API token for use in other API endpoints.\nPlease note that generating a new token will invalidate any existing tokens.\nYou should not share your token, and should keep your token safe and secure, e.g. using a password manager.\nYour token cannot be retrieved if it is lost, it must be regenerated.",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "required": ["token"],
                  "properties": {"token": {"type": "string"}}
                }
              }
            }
          }
        },
        "operationId": "getUserToken",
        "tags": ["users"]
      }
    },
    "/simulations/{id}/case-summary": {
      "get": {
        "description": "Retrieves summary result of simulation",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "Simulation ID",
            "schema": {"type": "integer"},
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {"$ref": "#/components/schemas/CaseSummary"}
              }
            }
          }
        },
        "operationId": "getSimulationCaseSummary",
        "tags": ["simulations"]
      }
    },
    "/simulations/{id}/download": {
      "get": {
        "description": "Downloads full result of simulation",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "Simulation ID",
            "schema": {"type": "integer"},
            "example": 2
          },
          {
            "in": "query",
            "name": "model",
            "required": true,
            "description": "Model slug",
            "schema": {"type": "string"},
            "example": "mrc-ide-covid-sim"
          }
        ],
        "responses": {
          "307": {
            "description": "Successful redirect",
            "headers": {
              "Location": {
                "description": "The URL to download results from",
                "schema": {"type": "string"}
              }
            }
          }
        },
        "operationId": "getSimulationDownload",
        "tags": ["simulations"]
      }
    },
    "/simulations/{id}/export": {
      "get": {
        "description": "Downloads full result of simulation",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "Simulation ID",
            "schema": {"type": "integer"},
            "example": 84
          },
          {
            "in": "query",
            "name": "model",
            "required": true,
            "description": "Model slug",
            "schema": {"type": "string"},
            "example": "mrc-ide-covid-sim"
          },
          {
            "in": "query",
            "name": "format",
            "description": "Determines what data and media type to return:\n \n * results -> application/json\n * crystalcast -> text/csv",
            "default": "results",
            "schema": {
              "type": "string",
              "$ref": "#/components/schemas/ExportFormat"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful export",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {"$ref": "#/components/schemas/ModelOutput"}
              },
              "text/csv": {
                "schema": {"type": "string"},
                "examples": {
                  "success": {"externalValue": "/export-example.csv"}
                }
              }
            }
          }
        },
        "operationId": "getSimulationExport",
        "tags": ["simulations"]
      }
    }
  },
  "components": {
    "schemas": {
      "CaseSummary": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "properties": {
            "cConf": {"type": "number"},
            "cHosp": {"type": "number"},
            "cDeaths": {"type": "number"},
            "peakDeath": {"$ref": "#/components/schemas/ISODate"},
            "peakDailyDeath": {"type": "number"},
            "modelVersion": {"type": "string"}
          },
          "required": [
            "cConf",
            "cHosp",
            "cDeaths",
            "peakDeath",
            "peakDailyDeath"
          ],
          "additionalProperties": false
        }
      },
      "ExportFormat": {"type": "string", "enum": ["results", "crystalcast"]},
      "Intensity": {
        "type": "string",
        "enum": ["aggressive", "moderate", "mild"],
        "title": "Intensity"
      },
      "InterventionPeriod": {
        "type": "object",
        "properties": {
          "startDate": {
            "$ref": "#/components/schemas/ISODate",
            "description": "An ISO-8601 string encoding the date that these interventions begin."
          },
          "socialDistancing": {
            "$ref": "#/components/schemas/Intensity",
            "description": "The level of social distancing in the region."
          },
          "schoolClosure": {
            "$ref": "#/components/schemas/Intensity",
            "description": "The level of school closure in the region."
          },
          "caseIsolation": {
            "$ref": "#/components/schemas/Intensity",
            "description": "The level to which individuals with symptoms self-isolate."
          },
          "voluntaryHomeQuarantine": {
            "$ref": "#/components/schemas/Intensity",
            "description": "The level to which entire households self-isolate when one member of the household has symptoms."
          },
          "reductionPopulationContact": {
            "type": "number",
            "description": "The estimated reduction in population contact resulting from all of the above interventions.\nSome models require this generalized parameter instead of the individual interventions."
          }
        },
        "required": ["startDate", "reductionPopulationContact"],
        "additionalProperties": false,
        "description": "Each intervention period is specified by a `startDate`, a set of interventions (`socialDistancing`, `caseIsolation`, `voluntaryHomeQuarantine`, and `schoolClosure`), and an estimate of the overall effect of these interventions (`reductionPopulationContact`).\nThis overall estimate is needed because some models do not simulate the effects of individual interventions.\nThe strictness of each intervention is specified roughly, as one of `mild`, `moderate`, or `aggressive`.\nEach model connector is responsible for interpreting this distinction in a way that works for the particular model.",
        "title": "Intervention Period"
      },
      "ISODate": {
        "type": "string",
        "title": "ISO Date",
        "example": "2020-03-06"
      },
      "ModelDescription": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "A short display name to identify the model"
          },
          "modelVersion": {
            "type": "string",
            "description": "A version number identifying the version of the model used in this run."
          },
          "connectorVersion": {
            "type": "string",
            "description": "A version number identifying the version of the connector used in this run.\nThis may be the same as modelVersion if development of the two is closely-linked."
          }
        },
        "required": ["name", "modelVersion", "connectorVersion"],
        "additionalProperties": false,
        "title": "Model Description"
      },
      "CommonModelInput": {
        "type": "object",
        "properties": {
          "region": {
            "$ref": "#/components/schemas/Region",
            "description": "The desired geographical top-level region for the simulation.\nConnector must check this value (and subregion, if provided) and and either produce results for that geography, or return an error."
          },
          "subregion": {
            "$ref": "#/components/schemas/Subregion",
            "description": "Specific subregion for the simulation.\nMay be omitted"
          },
          "parameters": {
            "$ref": "#/components/schemas/ModelParameters",
            "description": "Desired parameters.\nConnectors may choose to ignore any of these parameters if they wish."
          }
        },
        "required": ["region", "parameters"],
        "additionalProperties": false,
        "description": "A generalized description of the input to an epidemiological model.",
        "title": "Common Model Input"
      },
      "MinimalModelInput": {
        "type": "object",
        "properties": {
          "p": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Vector of model parameters"
          },
          "u0": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Vector of initial conditions"
          },
          "tspan": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Timespan over which to simulate the model"
          },
          "dt": {
            "type": "number",
            "description": "Optional time interval at which to compute the states."
          }
        },
        "required": ["p", "u0", "tspan"],
        "additionalProperties": false,
        "title": "Minimal Model Input"
      },
      "ModelInput": {
        "anyOf": [
          {"$ref": "#/components/schemas/CommonModelInput"},
          {"$ref": "#/components/schemas/MinimalModelInput"}
        ],
        "title": "Model Input"
      },
      "CommonModelOutput": {
        "type": "object",
        "properties": {
          "metadata": {"$ref": "#/components/schemas/CommonModelInput"},
          "model": {"$ref": "#/components/schemas/ModelDescription"},
          "time": {
            "type": "object",
            "properties": {
              "t0": {
                "type": "string",
                "description": "An ISO-8601 string encoding the date that each timeseries begins."
              },
              "timestamps": {
                "type": "array",
                "items": {"type": "number"},
                "description": "The timestamps that correspond to every series of metrics.\nEach value is a number of days after `t0`."
              },
              "extent": {
                "type": "array",
                "minItems": 2,
                "items": [{"type": "number"}, {"type": "number"}],
                "maxItems": 2,
                "description": "The minimum and maximum timestamps for the series of reported metrics.\nEach value is a number of days after `t0`."
              }
            },
            "required": ["t0", "timestamps", "extent"],
            "additionalProperties": false
          },
          "aggregate": {
            "type": "object",
            "properties": {
              "metrics": {"$ref": "#/components/schemas/SeverityMetrics"}
            },
            "required": ["metrics"],
            "additionalProperties": false
          }
        },
        "required": ["metadata", "model", "time", "aggregate"],
        "additionalProperties": false,
        "title": "Common Model Output"
      },
      "MinimalModelOutput": {
        "type": "object",
        "properties": {
          "metadata": {"$ref": "#/components/schemas/MinimalModelInput"},
          "model": {"$ref": "#/components/schemas/ModelDescription"},
          "t": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Vector of times at which the model is run"
          },
          "u": {
            "type": "array",
            "items": {"type": "array", "items": {"type": "number"}},
            "description": "Matrix of states"
          },
          "outputs": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Optional vector of outputs"
          }
        },
        "required": ["metadata", "model", "t", "u"],
        "additionalProperties": false,
        "title": "Minimal Model Output"
      },
      "ModelOutput": {
        "anyOf": [
          {"$ref": "#/components/schemas/CommonModelOutput"},
          {"$ref": "#/components/schemas/MinimalModelOutput"}
        ],
        "title": "Model Output"
      },
      "ModelParameters": {
        "type": "object",
        "properties": {
          "calibrationDate": {
            "$ref": "#/components/schemas/ISODate",
            "description": "An ISO-8601 string encoding the date of the most recent case data in the region.\nSome models such as `CovidSim` require you to provide some information about recorded cases in the region, in order to calibrate the model.\nThe web-interface provides this information automatically, based on recorded case data downloaded daily from various international data sources."
          },
          "calibrationCaseCount": {
            "type": "number",
            "description": "The total number of confirmed cases in the region before the calibration date."
          },
          "calibrationDeathCount": {
            "type": "number",
            "description": "The total number of deaths in the region before the calibration date."
          },
          "r0": {
            "type": "number",
            "description": "The assumed [_reproduction number_](https://en.wikipedia.org/wiki/Basic_reproduction_number) for the virus.\nIf this is null, then each model will use its own default value.",
            "nullable": true
          },
          "interventionPeriods": {
            "type": "array",
            "items": {"$ref": "#/components/schemas/InterventionPeriod"},
            "description": "A list of time periods, each with a different set of interventions.\nPolicy interventions are specified as a series of _intervention periods_, each with a certain set of interventions that are in place.\nFor example, case isolation and social distancing may be instituted first, followed by school closure a week later, followed by a relaxation of all guidelines after several months.\n**Note** - In order to specify that _all_ interventions end on a certain date, there should be a _final_ intervention period that starts on that date, has no interventions specified, and has `reductionPopulationContact` set to zero."
          }
        },
        "required": [
          "calibrationDate",
          "calibrationCaseCount",
          "calibrationDeathCount",
          "r0",
          "interventionPeriods"
        ],
        "additionalProperties": false,
        "title": "Model Parameters"
      },
      "ModelRun": {
        "type": "object",
        "properties": {
          "model_slug": {"type": "string"},
          "status": {"$ref": "#/components/schemas/RunStatus"},
          "results_data": {"type": "string", "nullable": true},
          "export_location": {"type": "string", "nullable": true}
        },
        "required": ["model_slug", "status", "results_data", "export_location"],
        "additionalProperties": false
      },
      "NewModelRunConfig": {
        "type": "object",
        "properties": {
          "model_slug": {"type": "string", "example": "mrc-ide-covid-sim"},
          "config": {"$ref": "#/components/schemas/ModelInput"}
        },
        "required": ["model_slug", "config"],
        "additionalProperties": false
      },
      "NewSimulationConfig": {
        "type": "object",
        "properties": {
          "regionID": {"$ref": "#/components/schemas/Region"},
          "subregionID": {"$ref": "#/components/schemas/Subregion"},
          "label": {"type": "string"},
          "r0": {"type": "number", "example": 1},
          "customCalibrationDate": {"$ref": "#/components/schemas/ISODate"},
          "interventionPeriods": {
            "type": "array",
            "items": {"$ref": "#/components/schemas/InterventionPeriod"}
          }
        },
        "required": ["regionID", "label", "interventionPeriods"],
        "additionalProperties": false,
        "description": "The data sent from web UI to backend"
      },
      "Region": {"type": "string", "title": "Region", "example": "US"},
      "RunStatus": {
        "type": "string",
        "enum": ["pending", "in-progress", "complete", "unsupported", "failed"],
        "title": "Run Status"
      },
      "SeverityMetrics": {
        "type": "object",
        "properties": {
          "Mild": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Current number of mild cases on this day"
          },
          "ILI": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Current number of influenza-like illness cases on this day (assume represents GP demand)"
          },
          "SARI": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Current number of Severe Acute Respiratory Illness cases on this day (assume represents hospital demand)"
          },
          "Critical": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Current number of critical cases on this day (assume represents ICU demand)"
          },
          "CritRecov": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Current number of critical cases on this day who are well enough to leave the ICU but still need a hospital bed"
          },
          "incDeath": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Number of deaths occurring on this day"
          },
          "cumMild": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Total number of mild cases since the beginning of the epidemic"
          },
          "cumILI": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Total number of influenza-like illnesses since the beginning of the epidemic"
          },
          "cumSARI": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Total number of severe acute respiratory illnesses since the beginning of the epidemic"
          },
          "cumCritical": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Total number of critical cases since the beginning of the epidemic"
          },
          "cumCritRecov": {
            "type": "array",
            "items": {"type": "number"},
            "description": "Total number of patients recovered from critical cases since the beginning of the epidemic"
          },
          "R": {
            "type": "array",
            "items": {"type": "number"},
            "description": "R-number on this day"
          }
        },
        "required": [
          "Mild",
          "ILI",
          "SARI",
          "Critical",
          "CritRecov",
          "incDeath",
          "cumMild",
          "cumILI",
          "cumSARI",
          "cumCritical",
          "cumCritRecov"
        ],
        "additionalProperties": false,
        "description": "The output contains a number of time series which represent predicted metrics about the epidemic.\nThree kinds of metrics are reported:\n- **Current values** - These metrics (e.g. `Mild`, `Critical`) represent the current number of patients in a given condition, on a particular date. For example, the `Critical` value at a given timestamp represents the number of patients in critical condition on that day.\n- **Cumulative values** - These metrics (e.g. `cumMild`, `cumCritical`) represent the total number of people who have been afflicted with a given condition since the beginning of the epidemic. For example, the `cumCritical` value at a given timestamp represents the total number of people who had been in critical condition due to the virus any time leading up to that day.\n- **Incidence values** - The `incDeath` metric represents the number of patients who died of the virus on a given day.\nEach output is an array corresponding to the `extent` specified above (i.e. with the same length as `timestamps`).\nOther than for `R` all numbers must be integers.\nNot all output parameters may be appropriate for your model.\nAll keys (except `R`) in the `aggregate` object are required however.\nIf a particular metric is not supported an array of zeros can be given.\nFor `R`, if your model does not produce this, you can simply omit the key.",
        "title": "Severity Metrics"
      },
      "SimulationSummary": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "configurationSummary": {"type": "string"},
          "id": {"type": "number"},
          "region_name": {"type": "string"},
          "status": {"$ref": "#/components/schemas/RunStatus"},
          "subregion_name": {"type": "string"},
          "region_id": {"type": "string"},
          "subregion_id": {"type": "string"},
          "github_user_id": {"type": "number"},
          "github_user_login": {"type": "string"},
          "model_runs": {
            "type": "array",
            "items": {"$ref": "#/components/schemas/ModelRun"}
          },
          "label": {"type": "string"},
          "created_at": {"type": "string"},
          "updated_at": {"type": "string"}
        },
        "required": [
          "configurationSummary",
          "created_at",
          "github_user_id",
          "github_user_login",
          "id",
          "model_runs",
          "region_name",
          "status",
          "updated_at"
        ]
      },
      "Subregion": {"type": "string", "title": "Subregion", "example": "US-AK"}
    },
    "securitySchemes": {
      "token": {
        "type": "http",
        "in": "header",
        "name": "Authorization",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Primary authentication method for programmatic use."
      },
      "session": {
        "type": "http",
        "in": "cookie",
        "name": "session",
        "description": "For use in UI. Also requires valid session.sig cookie"
      }
    }
  }
}
